library(shiny)
library(htmltools)
library(shinydashboard)
library(shinydashboardPlus)
library(NGLVieweR)
library(bsplus)
library(colourpicker)
library(shinyWidgets)
library(shinyjs)
library(r2d3)
library(shinyjqui)
library(readr)
library(dplyr)
library(stringr)
library(tidyr)
library(uuid)

shinyApp(ui = app_ui, server = app_server)
